The readonly keywords have been removed, the code is closer to the POSIX standard, all comments and the function for reference have been rewritten in English, the functions have changed their name to a more understandable one

diff --git a/alterator-diag-domain-controller b/alterator-diag-domain-controller
--- a/alterator-diag-domain-controller
+++ b/alterator-diag-domain-controller
@@ -1,8 +1,8 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Copyright (C) 2024 Evgeny Sinelnikov <sin@altlinux.org>
 # Copyright (C) 2024 Sergey Savelev <savelevsa@basealt.ru>
 #
-# A tool for diagnosing the status of a domain controller
+# The Domain Controller Status Diagnostic Utility
 #
 # This program is free software: you can redistribute it and/or modify
 #
@@ -12,38 +12,39 @@ set -euo pipefail
 
 . shell-getopt
 
-readonly PROG_NAME="${0##*/}"
-readonly VERSION="0.0.1"
-readonly task_list="$*"
+PROG_NAME="${0##*/}"
+VERSION="0.0.1"
+global_retval=0
+task_list="$*"
 cmd="run"
 
 # Function for displaying the program version
-print_version(){
+print_version() {
     cat <<EOF
-Версия программы $PROG_NAME - $VERSION
+$PROG_NAME version $VERSION
 EOF
     exit 0
 }
 
-# A function for displaying background information
-show_usage(){
+# The function outputs reference information
+show_usage() {
     cat <<EOF
-$PROG_NAME - инструмент диагностики состояния контроллера домена
+$PROG_NAME - The Domain Controller Status Diagnostic Utility
 
-Формат вызова: $PROG_NAME [options] [<diagnostic-task>]
+Usage: $PROG_NAME [options] [<diagnostic-task>]
 
 Опции:
-    -l, --list			Список диагностических задач
-    -v, --version		Вывод версии утилиты
-    -h, --help			Показать данную справку и выйти
+    -l, --list			list of diagnostic tasks
+    -V, --version		print program version and exit
+    -h, --help			show this text and exit
 EOF
     exit 0
 }
 
-readonly TEMP=$(getopt -n "${0##*/}" -o "l,v,r,h", -l "list,version,report,help" -- "$@") || show_usage
+TEMP=$(getopt -n "${0##*/}" -o "l,v,r,h", -l "list,version,report,help" -- "$@") || show_usage
 eval set -- "$TEMP"
 
-while true; do
+while :; do
     case "$1" in
 	-l|--list)
 	    cmd="list"
@@ -71,13 +72,13 @@ while true; do
 done
 
 # A function for displaying a list of tests
-task_show(){
+task_show() {
     local func="$1"
     echo "$func"
 }
 
 # Function for running tests
-task_run(){
+task_run() {
     local retval=126
     local func="$1"
 
@@ -86,13 +87,13 @@ task_run(){
     fi
 
     $func && retval=0 || retval="$?"
-    test $retval=0
+    test $retval=0 || global_retval=1
 
     return $retval
 }
 
 # Depending on the parameter of the cmd variable, the function decides what to run
-task(){
+task() {
     local task="$1"
 
     case "$cmd" in
@@ -111,49 +112,40 @@ task(){
     esac
 }
 
-# A function for viewing general domain information
-check_domain_info(){
+# Checking the availability of viewing general domain information
+is_domain_info_available() {
     local retval=0
-    output="$(samba-tool domain info 127.0.0.1 2>&1)"
-    command_status=$?
 
-    if [[ "$command_status" -ne 0 ]]; then
-	retval=1
-    else
-	if [[ "$output" == *"ERROR: Invalid IP address '127.0.0.1'!"* ]]; then
-	    retval=1
-	fi
-    fi
+    samba-tool domain info 127.0.0.1 &> /dev/null || retval=1
 
     return $retval
 }
 
-# Checking the full domain name of the host (FQDN)
-test_hostname(){
+# Checking the correct spelling of the domain name of the host
+is_hostname_correct() {
     local retval=0
-    local host="$(hostname -f)"
 
-    { [[ "$host" == *.* ]] && [[ "$host" != $.* ]] && [[ "$(host "$host")" ]]; } || retval=2
+    hostnamectl | head -n1 | awk '{print $NF}' | grep "^[^.]*\..*" &> /dev/null || retval=1
 
     return $retval
 }
 
-# The sysvol directory size check function
-is_not_empty_sysvol(){
+# Checking if the sysvol directory is empty
+is_not_empty_sysvol() {
     local retval=0
 
-    if [ -z "$(ls -A "/var/lib/samba/sysvol" 2> /dev/null)" ]; then
-	retval=2
-    fi
+    test -n "$(ls -A /var/lib/samba/sysvol 2> /dev/null)" || retval=2
 
     return $retval
 }
 
-task check_domain_info
-task test_hostname
+task is_domain_info_available
+task is_hostname_correct
 task is_not_empty_sysvol
 
-# TODO: Написать остальные функции для тестов
-# TODO: Добавить функцию для составления и вывода отчёта в файл отчёта
-# TODO: В функции task() добавить результат [WARN]
-# TODO: Подумать над тем, как выводить результаты [DONE], [FAIL], [WARN]
+# TODO: It is planned to write the rest of the functions for the tests
+# TODO: Will need to add a logging feature
+# TODO: In the task() function, will need to add the result [WARN]
+# TODO: Will need to think about how to output the results of [DONE], [FAIL], [WARN]
+
+exit "$global_retval"
