Fix diag-domain-controller script and remove some strange tests:  * is_admx_basealt_package_installed  * task is_dns_forward_address_valid  * is_address_written_in_nameserver  * does_kerberos_work

diff --git a/diag-domain-controller b/diag-domain-controller
--- a/diag-domain-controller
+++ b/diag-domain-controller
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 # Copyright (C) 2024 Evgeny Sinelnikov <sin@altlinux.org>
 # Copyright (C) 2024 Andrey Limachko <liannnix@altlinux.org>
 # Copyright (C) 2024 Elena Dyatlenko <lenka@altlinux.org>
@@ -20,17 +20,15 @@ global_retval=0
 task_list="$*"
 cmd="run"
 
-# Function for displaying the program version
 print_version() {
-    cat <<EOF
+	cat <<EOF
 $PROG_NAME version $VERSION
 EOF
     exit 0
 }
 
-# The function outputs reference information
 show_usage() {
-    cat <<EOF
+	cat <<EOF
 $PROG_NAME - The Domain Controller Status Diagnostic Utility
 
 Usage: $PROG_NAME [options] [<diagnostic-task>]
@@ -47,235 +45,167 @@ TEMP=$(getopt -n "${0##*/}" -o "l,V,r,h", -l "list,version,report,help" -- "$@")
 eval set -- "$TEMP"
 
 while :; do
-    case "$1" in
-	-l|--list)
-	    cmd="list"
-	    shift
-	    ;;
-	-V|--version)
-	    print_version
-	    shift
-	    ;;
-	-r|--report)
-	    shift
-	    ;;
-	-h|--help)
-	    show_usage
-	    shift
-	    ;;
-	--)
-	    shift
-	    break
-	    ;;
-	*)
-	    fatal "Unrecognized option: $1"
-	    ;;
-    esac
+	case "$1" in
+		-l|--list)
+			cmd="list"
+			shift
+			;;
+		-V|--version)
+			print_version
+			shift
+			;;
+		-r|--report)
+			shift
+			;;
+		-h|--help)
+			show_usage
+			shift
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			fatal "Unrecognized option: $1"
+			;;
+	esac
 done
 
-# A function for displaying a list of tests
 task_show() {
-    local func="$1"
-    echo "$func"
+	local func="$1"
+	echo "$func"
 }
 
-# Function for running tests
 task_run() {
-    local retval=126
-    local func="$1"
+	local retval=126
+	local func="$1"
 
-    if test -n "$task_list"; then
-	echo "$task_list" | tr ' ' '\n' | grep -q "^$func\$" || return 0
-    fi
+	if test -n "$task_list"; then
+		echo "$task_list" | tr ' ' '\n' | grep -q "^$func\$" || return 0
+	fi
 
-    $func && retval=0 || retval="$?"
-    test $retval = 0 || global_retval=1
+	$func && retval=0 || retval="$?"
+	test $retval = 0 || global_retval=1
 
-    return $retval
+	return $retval
 }
 
 # Determining the test execution status
 test_status() {
-    local retval="$1"
-    local task="$2"
+	local retval="$1"
+	local task="$2"
 
-    case "$retval" in
-	0)
-	    echo "[DONE]: $task"
-	    ;;
-	1)
-	    echo "[FAIL]: $task"
-	    ;;
-	2)
-	    echo "[WARN]: $task"
-	    ;;
-	*)
-	    echo "[FAIL]: $task"
-	    ;;
-    esac
+	case "$retval" in
+		0) echo "[DONE]: $task"
+			;;
+		1) echo "[FAIL]: $task"
+			;;
+		2) echo "[WARN]: $task"
+			;;
+		*) echo "[FAIL]: $task"
+			;;
+	esac
 }
 
 # Depending on the parameter of the cmd variable, the function decides what to run
 task() {
-    local task="$1"
+	local task="$1"
 
-    case "$cmd" in
-	list)
-	    task_show "$task"
-	    ;;
-	report)
-	    ;;
-	run)
-	    if test -z "$task_list" || grep "$task" <<< "$task_list"; then
-		local retval=0
+	case "$cmd" in
+		list)
+			task_show "$task"
+			;;
+		report)
+			;;
+		run)
+			if test -z "$task_list" || grep "$task" <<< "$task_list"; then
+				local retval=0
 
-		task_run "$task" || retval="$?"
-		test_status "$retval" "$task"
-	    fi
-	    ;;
-	*)
-	    fatal "Unrecognized command: $cmd"
-	    ;;
-    esac
+				task_run "$task" || retval="$?"
+				test_status "$retval" "$task"
+			fi
+			;;
+		*)
+			fatal "Unrecognized command: $cmd"
+			;;
+	esac
 }
 
 # Checking the availability of viewing general domain information
 is_domain_info_available() {
-    local retval=0
+	local retval=0
 
-    samba-tool domain info 127.0.0.1 &> /dev/null || retval=1
+	/usr/bin/samba-tool domain info 127.0.0.1 &> /dev/null || retval=1
 
-    return $retval
+	return $retval
 }
 
 # Checking the correct spelling of the domain name of the host
 is_hostname_correct() {
-    local retval=0
+	local retval=0
 
-    hostnamectl | head -n1 | awk '{print $NF}' | grep "^[^.]*\..*" &> /dev/null || retval=1
+	hostname | grep "^[^.]*\..*" &> /dev/null || retval=1
 
-    return $retval
+	return $retval
 }
 
 # Checking if the sysvol directory is empty
 is_not_empty_sysvol() {
-    local retval=0
+	local retval=0
 
-    test -n "$(ls -A /var/lib/samba/sysvol 2> /dev/null)" || retval=2
+	test -n "$(ls -A /var/lib/samba/sysvol 2> /dev/null)" || retval=2
 
-    return $retval
+	return $retval
 }
 
 # Checking for the samba package in the system
 is_samba_package_installed() {
-    local retval=0
-    local packet_name=
+	local retval=0
+	local heimdal_name="samba-dc"
+	local mit_name="samba-dc-mitkrb5"
 
-    packet_name="samba"
+	rpm -q "$heimdal_name" &> /dev/null || rpm -q "$mit_name" &> /dev/null && retval=0 || retval=1
 
-    rpm -qi "$packet_name" &> /dev/null || retval=1
-
-    return $retval
-}
-
-# Checking for the admx-basealt package in the system
-is_admx_basealt_package_installed() {
-    local retval=0
-    local packet_name=
-
-    packet_name="admx-basealt"
-
-    rpm -qi "$packet_name" &> /dev/null || retval=1
-
-    return $retval
+	return $retval
 }
 
 # Checking whether the Samba service is running
 is_samba_service_running() {
-    local retval=0
-    local service=
+	local retval=0
+	local service=
 
-    service="samba.service"
+	service="samba.service"
 
-    systemctl status "$service" &> /dev/null || retval=1
+	systemctl status "$service" &> /dev/null || retval=1
 
-    return $retval
+	return $retval
 }
 
 # Samba databases are checked for errors
 are_there_errors_in_samba_databases() {
-    local retval=0
+	local retval=0
 
-    samba-tool dbcheck 2> /dev/null | grep -q "Checked \+[[:digit:]]\+ objects (0 errors)" || retval=1
+	/usr/bin/samba-tool dbcheck &> /dev/null || retval=1
 
-    return $retval
+	return $retval
 }
 
 # Time Synchronization Check - NTP service activity
 is_ntp_service_running() {
-    local retval=0
+	local retval=0
 
-    timedatectl | grep -q "NTP service: active" || retval=2
+	test "$(timedatectl show -p NTP --value)" = 'yes' || retval=2
 
-    return $retval
-}
-
-# Checking the operation of recursive dns queries - checking the validity of the dns forward address
-is_dns_forward_address_valid() {
-    local retval=0
-    local validate_ipv4=
-    local string_forwarder=
-
-    validate_ipv4="^(25[0-5]|2[0-4][0-9]|1?[0-9]{1,2})(\.(25[0-5]|2[0-4][0-9]|1?[0-9]{1,2})){3}$"
-    string_forwarder="$(grep "dns forwarder =" /etc/samba/smb.conf | awk '{print $4}')"
-
-    grep -E "$validate_ipv4" >/dev/null 2>&1 <<< "$string_forwarder" || retval=2
-
-    return $retval
-}
-
-# Checking for own address next to the nameserver string
-is_address_written_in_nameserver() {
-    local retval=0
-    local ip_addr=
-    local nameservers=
-
-    ip_addr="$(hostname -i)"
-    nameservers="$(grep "nameserver " /etc/resolv.conf | awk '{print $2}')"
-
-    if echo "$nameservers" | grep -q "^$ip_addr$" || echo "$nameservers" | grep -q "127.0.0.1"; then
-	retval=0
-    else
-	retval=2
-    fi
-
-    return $retval
-}
-
-# Checking the health of kerberos and ldap - there must be appropriate records
-does_kerberos_work() {
-    local retval=0
-    local hostname=
-
-    hostname="$(hostnamectl | head -n1 | awk '{printf $NF}' | cut -f2- -d.)"
-
-    host -t srv _kerberos._udp."$hostname" | grep "has SRV record 0 100 88" &> /dev/null || retval=1
-    host -t srv _ldap._tcp."$hostname" | grep "has SRV record 0 100 389" &> /dev/null || retval=1
-
-    return $retval
+	return $retval
 }
 
 task is_domain_info_available
 task is_hostname_correct
 task is_not_empty_sysvol
 task is_samba_package_installed
-task is_admx_basealt_package_installed
 task is_samba_service_running
 task are_there_errors_in_samba_databases
 task is_ntp_service_running
-task is_dns_forward_address_valid
-task is_address_written_in_nameserver
-task does_kerberos_work
 
 # TODO: It is planned to write the rest of the functions for the tests
 # TODO: Will need to add a logging feature
