Added a function that determines the result of the test

diff --git a/sambadc-diag b/sambadc-diag
--- a/sambadc-diag
+++ b/sambadc-diag
@@ -66,3 +66,14 @@ task_run(){
 
     return $retval
 }
+
+task(){
+    local task="$1"
+    
+    case "$cmd" in
+	list) task_show "$task" ;;
+	report) ;;
+	run) task_run "$task" && echo "[DONE]: $task" || echo "[FAIL]: $task" ;;
+	*) fatal "Неверное значение: $cmd" ;;
+    esac
+}
